name: First Node.js Workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Code from Repo
              uses: actions/checkout@v3
            - name: install  nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: install dependencies
              run: npm insall
            - name: RUn Test for Nodejs
              run: npm test
